"""Match conda-forge packages to OSV advisories via their PURL mapping.

For each package with at least one PURL in ``web/public/mappings.json``
(generated by :mod:`scripts.merge_mappings`), this script:

1. Looks up OSV advisories whose ``affected[].package`` references that PURL
   (or any of its alternatives).
2. Enumerates every conda-forge version of the package via
   ``rattler.repo_data.Gateway``.
3. Intersects each advisory's affected-version *ranges* (or explicit version
   list) with the set of conda-forge versions, producing the set of conda
   versions believed to be vulnerable.
4. Writes one JSON file per package to ``mappings/cves/<pkg>.json``. Each
   advisory in that file is the OSV record with minimal schema repairs for
   malformed upstream range events so it validates against the official OSV
   schema (``schemas/osv-schema.json``). The conda-forge match — affected
   versions, the conda PURL, the source PURL the match came through — is
   attached under the record's
   ``database_specific["conda-forge"]`` key, the OSV-sanctioned extension slot
   for downstream database-specific data.

The version comparison defaults to a direct upstream-vs-conda match using
``rattler.version.Version`` (which understands both PEP 440-ish PyPI versions
and conda's epoch/local extensions). Manual *version overrides* recorded in
``mappings/cve_contributions/`` flip individual versions when this default
mistranslates — :mod:`scripts.merge_cves` applies those during the merge.
"""

from __future__ import annotations

import asyncio
import copy
import json
import re
import sys
import time
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import typer
from rattler.platform import Platform
from rattler.repo_data import Gateway, RepoDataRecord, SourceConfig
from rattler.version import Version
from rich.console import Console
from rich.progress import (
    BarColumn,
    MofNCompleteColumn,
    Progress,
    TextColumn,
    TimeElapsedColumn,
)

from scripts.cve_common import conda_purl
from scripts.osv_fetch import (
    PURL_TO_OSV,
    Advisory,
    OsvIndex,
    fetch_index,
)

app = typer.Typer(add_completion=False, help=__doc__)
console = Console()

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MAPPINGS = ROOT / "web" / "public" / "mappings.json"
DEFAULT_OUT_DIR = ROOT / "mappings" / "cves"
DEFAULT_OSV_CACHE = ROOT / "osv_cache"
DEFAULT_PLATFORMS = ("linux-64", "noarch")
DEFAULT_CHANNEL = "conda-forge"


# ---------- PURL parsing ----------


@dataclass(frozen=True)
class ParsedPurl:
    type: str
    namespace: str | None
    name: str

    def to_string(self) -> str:
        if self.namespace:
            return f"pkg:{self.type}/{self.namespace}/{self.name}"
        return f"pkg:{self.type}/{self.name}"


def parse_purl(purl: str) -> ParsedPurl | None:
    if not purl.startswith("pkg:"):
        return None
    body = purl[len("pkg:") :]
    # Strip any qualifiers / subpath / version that may be appended.
    for sep in ("?", "#", "@"):
        idx = body.find(sep)
        if idx >= 0:
            body = body[:idx]
    parts = body.split("/")
    if len(parts) < 2:
        return None
    ptype = parts[0].lower()
    if len(parts) == 2:
        return ParsedPurl(ptype, None, parts[1])
    namespace = "/".join(parts[1:-1])
    return ParsedPurl(ptype, namespace, parts[-1])


# ---------- Version intersection ----------


def _safe_version(text: str) -> Version | None:
    try:
        return Version(text)
    except Exception:
        return None


def _event_to_version(value: object) -> Version | None:
    if not isinstance(value, str) or not value:
        return None
    if value == "0":
        return None  # treat as "open-ended below"
    return _safe_version(value)


def version_in_affected_entry(version: Version, entry: dict) -> bool:
    """Decide whether ``version`` falls inside one OSV ``affected[]`` entry.

    Per the OSV schema:

    - ``versions`` is an *exhaustive enumeration* of affected versions. If it
      exists and the version isn't listed, it isn't affected (regardless of
      what ``ranges`` says).
    - ``ranges`` contain an ordered ``events`` list with sentinel events:
      ``introduced``, ``fixed`` (exclusive upper bound), ``last_affected``
      (inclusive upper bound), and ``limit`` (treated like ``fixed``).
    - A ``GIT`` range is ignored — we can't compare git SHAs against
      ecosystem versions.

    We treat both ``SEMVER`` and ``ECOSYSTEM`` ranges uniformly: rattler's
    ``Version`` is permissive enough to order both. If neither ``versions``
    nor any usable ``ranges`` exist, we fail closed (return False).
    """
    versions = entry.get("versions")
    if isinstance(versions, list) and versions:
        for v in versions:
            if not isinstance(v, str):
                continue
            try:
                if Version(v) == version:
                    return True
            except Exception:
                continue
        return False

    ranges = entry.get("ranges")
    if not isinstance(ranges, list):
        return False

    for rng in ranges:
        if not isinstance(rng, dict):
            continue
        if rng.get("type") == "GIT":
            continue
        events = rng.get("events")
        if not isinstance(events, list):
            continue
        introduced: Version | None = None
        introduced_open = False  # ``introduced: "0"``
        for ev in events:
            if not isinstance(ev, dict):
                continue
            if "introduced" in ev:
                raw = ev["introduced"]
                if raw == "0":
                    introduced = None
                    introduced_open = True
                else:
                    introduced = _event_to_version(raw)
                    introduced_open = False
            elif "fixed" in ev or "limit" in ev:
                cap = _event_to_version(ev.get("fixed") or ev.get("limit"))
                if cap is None:
                    introduced = None
                    introduced_open = False
                    continue
                lower_ok = introduced_open or (
                    introduced is not None and version >= introduced
                )
                if lower_ok and version < cap:
                    return True
                introduced = None
                introduced_open = False
            elif "last_affected" in ev:
                cap = _event_to_version(ev["last_affected"])
                if cap is None:
                    introduced = None
                    introduced_open = False
                    continue
                lower_ok = introduced_open or (
                    introduced is not None and version >= introduced
                )
                if lower_ok and version <= cap:
                    return True
                introduced = None
                introduced_open = False
        # Range ended without a closing event: the introduction is still open.
        if introduced_open:
            return True
        if introduced is not None and version >= introduced:
            return True
    return False


# ---------- per-package processing ----------


@dataclass
class CondaVersion:
    version: str
    parsed: Version
    builds: list[str]  # build strings observed for this version (any subdir)
    latest_timestamp: str | None


def _aggregate_conda_versions(records: Iterable[RepoDataRecord]) -> list[CondaVersion]:
    by_version: dict[str, CondaVersion] = {}
    for r in records:
        vs = str(r.version)
        parsed = _safe_version(vs)
        if parsed is None:
            continue
        existing = by_version.get(vs)
        ts = r.timestamp.isoformat() if r.timestamp else None
        if existing is None:
            by_version[vs] = CondaVersion(
                version=vs, parsed=parsed, builds=[r.build], latest_timestamp=ts
            )
        else:
            if r.build not in existing.builds:
                existing.builds.append(r.build)
            if ts and (
                existing.latest_timestamp is None or ts > existing.latest_timestamp
            ):
                existing.latest_timestamp = ts
    return sorted(by_version.values(), key=lambda c: c.parsed)


_EVENT_KEYS = frozenset({"introduced", "fixed", "last_affected", "limit"})

# OSV schema GIT-range pattern: the special value "0" or a 40/64-char hex hash.
_GIT_HASH_RE = re.compile(r"^(0|[a-f0-9]{40}|[a-f0-9]{64})$")


def _sanitize_git_event(ev: dict) -> dict | None:
    """Coerce a GIT range event's values to the OSV schema's hash pattern.

    Upstream OSV occasionally publishes commit hashes with stray trailing
    punctuation (PYSEC-2023-80 vyper: ``02339dfd...c520.``). Try a lowercase +
    trailing-non-hex strip; if the result still doesn't match the schema's
    pattern, drop the offending key. An event with no remaining keys is
    returned as ``None`` so the caller can drop it like an empty event."""
    cleaned: dict = {}
    for key, value in ev.items():
        if key in _EVENT_KEYS and isinstance(value, str):
            candidate = re.sub(r"[^0-9a-f]+$", "", value.strip().lower())
            if not _GIT_HASH_RE.match(candidate):
                continue
            cleaned[key] = candidate
        else:
            cleaned[key] = value
    if not (_EVENT_KEYS & cleaned.keys()):
        return None
    return cleaned


def _repair_osv_record(record: dict) -> dict:
    """Strip malformed range events from a verbatim OSV record, in place.

    OSV occasionally publishes records with empty ``{}`` range events (seen on
    several 2025 PYSEC ``transformers`` advisories) or GIT events whose commit
    hash has stray trailing characters (PYSEC-2023-80 vyper). Both fail
    OSV-schema validation — so we drop the empty events, sanitize the GIT hash
    where possible, and drop any range left without a usable event. Nothing
    else in the record is altered."""
    for affected in record.get("affected") or []:
        if not isinstance(affected, dict) or not isinstance(
            affected.get("ranges"), list
        ):
            continue
        repaired: list[dict] = []
        for rng in affected["ranges"]:
            if not isinstance(rng, dict):
                continue
            events = rng.get("events")
            if isinstance(events, list):
                is_git = rng.get("type") == "GIT"
                cleaned: list[dict] = []
                for ev in events:
                    if not isinstance(ev, dict) or not (_EVENT_KEYS & ev.keys()):
                        continue
                    if is_git:
                        fixed_ev = _sanitize_git_event(ev)
                        if fixed_ev is None:
                            continue
                        cleaned.append(fixed_ev)
                    else:
                        cleaned.append(ev)
                if not cleaned:
                    continue  # range with no usable events — drop it
                rng["events"] = cleaned
            repaired.append(rng)
        affected["ranges"] = repaired
    return record


def _affects_future_version(adv: Advisory, latest: Version | None) -> bool:
    """True iff some upstream-affected version is strictly newer than the
    latest conda-forge version of the package.

    This is the "we lag behind upstream" signal: the advisory's affected set
    includes a version conda-forge hasn't shipped yet, so a future release
    will be vulnerable on arrival. Treat it as a triage priority — gives
    maintainers a chance to block the upload or patch before it lands.

    Sources checked:
    * Explicit ``affected[].versions`` list (e.g. mistralai's
      ``GHSA-wx9m-wx4f-4cmg`` which enumerates ``["2.4.6"]``).
    * Range events with ``introduced > latest`` — the bug is introduced at a
      version we don't have yet, so all conda-forge releases that catch up
      to it will be vulnerable.

    Returns False when ``latest`` is unknown or every reachable affected
    version is at/below it (the standard "active on latest" case is handled
    separately)."""
    if latest is None:
        return False
    entry = adv.raw_affected
    for v in entry.get("versions") or []:
        parsed = _safe_version(v)
        if parsed is not None and parsed > latest:
            return True
    for rng in entry.get("ranges") or []:
        if not isinstance(rng, dict) or rng.get("type") == "GIT":
            continue
        for ev in rng.get("events") or []:
            if not isinstance(ev, dict):
                continue
            introduced = ev.get("introduced")
            if isinstance(introduced, str):
                parsed = _safe_version(introduced)
                if parsed is not None and parsed > latest:
                    return True
    return False


def _build_osv_record(
    adv: Advisory,
    affected_versions: list[str],
    *,
    conda_package: str,
    source_purls: list[str],
    conda_versions_total: int,
    latest_version: Version | None,
    generated_at: str,
) -> dict:
    """Re-emit the OSV record with the conda-forge match attached.

    Apart from minimal schema repairs for malformed upstream range events, the
    record follows the advisory OSV published. Our derived data — which
    conda-forge versions are affected, the conda PURL, which source PURL the
    match came through, whether the advisory targets a future version we
    don't ship yet — goes into ``database_specific["conda-forge"]``, the
    OSV-sanctioned extension slot for database-specific fields. ``conda-forge``
    is not an OSV ecosystem, so it cannot be a real ``affected[]`` entry."""
    record = _repair_osv_record(copy.deepcopy(adv.raw))
    db = record.get("database_specific")
    if not isinstance(db, dict):
        db = {}
    db["conda-forge"] = {
        "package": conda_package,
        "purl": conda_purl(conda_package),
        "source_purls": source_purls,
        "affected_versions": affected_versions,
        "conda_versions_total": conda_versions_total,
        "affects_future": _affects_future_version(adv, latest_version),
        "derived_by": "purl-associator/scripts.cve_match",
        "generated_at": generated_at,
    }
    record["database_specific"] = db
    return record


def _match_advisories(
    purls: list[ParsedPurl], osv: OsvIndex, versions: list[CondaVersion]
) -> dict[str, tuple[Advisory, list[str]]]:
    """Map each matched OSV id to ``(advisory, affected_conda_versions)``.

    The same advisory may legitimately match more than one PURL (e.g. a numpy
    CVE indexed under both the PyPI and npm names). We dedupe by OSV id and
    union the affected conda versions across whichever PURL matched it."""
    seen: dict[str, tuple[Advisory, set[str]]] = {}
    for purl in purls:
        for adv in osv.for_purl(purl.type, purl.name):
            entry = adv.raw_affected
            affected: set[str] = set()
            for v in versions:
                try:
                    if version_in_affected_entry(v.parsed, entry):
                        affected.add(v.version)
                except Exception:
                    # Defensive: a single broken OSV range shouldn't poison
                    # the whole package match. Skip the version, move on.
                    continue
            prev = seen.get(adv.id)
            if prev is None:
                seen[adv.id] = (adv, affected)
            else:
                seen[adv.id] = (prev[0], prev[1] | affected)
    return {
        adv_id: (adv, sorted(affected, key=lambda s: _safe_version(s) or Version("0")))
        for adv_id, (adv, affected) in seen.items()
    }


# ---------- I/O ----------


def _load_mappings(path: Path) -> dict[str, dict]:
    if not path.exists():
        raise typer.BadParameter(
            f"Mappings file not found: {path}. "
            "Run `pixi run python -m scripts.merge_mappings` first."
        )
    payload = json.loads(path.read_text())
    pkgs = payload.get("packages")
    if not isinstance(pkgs, dict):
        raise typer.BadParameter(f"Unexpected mappings shape in {path}")
    return pkgs


def _collect_purls(entry: dict) -> list[ParsedPurl]:
    purls: list[ParsedPurl] = []
    seen: set[str] = set()
    primary = entry.get("purl")
    if isinstance(primary, str):
        p = parse_purl(primary)
        if p and p.to_string() not in seen:
            purls.append(p)
            seen.add(p.to_string())
    for alt in entry.get("alternative_purls") or []:
        if not isinstance(alt, dict):
            continue
        alt_purl = alt.get("purl")
        if isinstance(alt_purl, str):
            p = parse_purl(alt_purl)
            if p and p.to_string() not in seen:
                purls.append(p)
                seen.add(p.to_string())
    # Filter: skip PURL types OSV doesn't index (e.g. github, generic).
    return [p for p in purls if p.type in PURL_TO_OSV]


def _write_file(out_dir: Path, name: str, payload: dict) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"{name}.json"
    target.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return target


async def _gather_records(
    *, channel: str, platforms: Iterable[str], names: list[str]
) -> dict[str, list[RepoDataRecord]]:
    gateway = Gateway(
        default_config=SourceConfig(
            sharded_enabled=True, cache_action="cache-or-fetch"
        ),
        show_progress=False,
    )
    platform_objs = [Platform(p) for p in platforms]
    by_source = await gateway.query(
        sources=[channel], platforms=platform_objs, specs=names, recursive=False
    )
    by_name: dict[str, list[RepoDataRecord]] = {}
    for source_records in by_source:
        for record in source_records:
            by_name.setdefault(record.name.normalized, []).append(record)
    return by_name


# ---------- main ----------


@dataclass
class RunSummary:
    packages_with_advisories: int
    advisories_total: int
    affected_version_total: int
    written_files: list[Path]
    skipped_no_purl: int
    skipped_no_advisories: int


@app.command()
def main(
    mappings: Path = typer.Option(DEFAULT_MAPPINGS, help="Merged PURL mappings JSON"),
    out_dir: Path = typer.Option(DEFAULT_OUT_DIR, help="Per-package CVE output dir"),
    channel: str = typer.Option(DEFAULT_CHANNEL, help="conda channel"),
    platforms: list[str] = typer.Option(
        list(DEFAULT_PLATFORMS), help="platforms to scan for versions"
    ),
    only: str | None = typer.Option(
        None, help="Comma-separated conda names to process (subset run)"
    ),
    limit: int | None = typer.Option(
        None, help="Process at most N candidate packages (test runs)"
    ),
    osv_cache: Path = typer.Option(DEFAULT_OSV_CACHE, help="OSV download cache dir"),
    osv_max_age_hours: float = typer.Option(
        6.0, help="Re-download OSV dump if older than this"
    ),
    force_osv: bool = typer.Option(False, help="Force re-download of OSV dumps"),
    clean_stale: bool = typer.Option(
        True,
        help="When running over the full channel, delete files for packages "
        "with no current advisories",
    ),
) -> None:
    """Refresh the per-package CVE JSON files."""
    asyncio.run(
        _async_main(
            mappings=mappings,
            out_dir=out_dir,
            channel=channel,
            platforms=platforms,
            only=only.split(",") if only else None,
            limit=limit,
            osv_cache=osv_cache,
            osv_max_age_hours=osv_max_age_hours,
            force_osv=force_osv,
            clean_stale=clean_stale,
        )
    )


async def _async_main(
    *,
    mappings: Path,
    out_dir: Path,
    channel: str,
    platforms: list[str],
    only: list[str] | None,
    limit: int | None,
    osv_cache: Path,
    osv_max_age_hours: float,
    force_osv: bool,
    clean_stale: bool,
) -> RunSummary:
    started = time.monotonic()
    pkgs = _load_mappings(mappings)
    if only:
        only_set = {o.strip() for o in only if o.strip()}
        pkgs = {k: v for k, v in pkgs.items() if k in only_set}
    if limit is not None:
        pkgs = dict(sorted(pkgs.items())[:limit])
    if not pkgs:
        console.log("No packages to process — exiting.")
        return RunSummary(0, 0, 0, [], 0, 0)
    console.log(f"Considering [bold]{len(pkgs):,}[/] packages from {mappings.name}")

    # Step 1: gather OSV index for just the PURL types in play.
    purl_types_used: set[str] = set()
    for entry in pkgs.values():
        for p in _collect_purls(entry):
            purl_types_used.add(p.type)
    if not purl_types_used:
        console.log("No PURLs reference an OSV-indexed ecosystem — nothing to match.")
        return RunSummary(0, 0, 0, [], len(pkgs), 0)
    console.log(
        f"OSV ecosystems in play: [bold]{', '.join(sorted(purl_types_used))}[/]"
    )
    osv = await fetch_index(
        cache_dir=osv_cache,
        purl_types=purl_types_used,
        force=force_osv,
        max_age_hours=osv_max_age_hours,
    )
    console.log(
        f"OSV index: {osv.total_advisories():,} affected-package entries "
        f"across {len(osv.dumps)} ecosystem(s)"
    )

    # Step 2: cheap pre-filter — which packages have at least one OSV hit?
    # No point fetching conda-forge versions for the other 24k.
    candidates: dict[str, list[ParsedPurl]] = {}
    skipped_no_purl = 0
    for name, entry in pkgs.items():
        purls = _collect_purls(entry)
        if not purls:
            skipped_no_purl += 1
            continue
        if any(osv.for_purl(p.type, p.name) for p in purls):
            candidates[name] = purls
    console.log(
        f"Candidates with ≥1 OSV hit: [bold]{len(candidates):,}[/] "
        f"({skipped_no_purl:,} skipped — no OSV-indexed PURL)"
    )
    if not candidates:
        if clean_stale and not only and not limit:
            _prune_stale(out_dir, keep=set())
        return RunSummary(0, 0, 0, [], skipped_no_purl, 0)

    # Step 3: enumerate conda versions for the candidates only.
    records_by_name = await _gather_records(
        channel=channel, platforms=platforms, names=list(candidates.keys())
    )

    # Step 4: per-candidate matching + write.
    written: list[Path] = []
    total_advs = 0
    total_affected_versions = 0
    generated_at = datetime.now(UTC).isoformat(timespec="seconds")

    with Progress(
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        MofNCompleteColumn(),
        TimeElapsedColumn(),
        console=console,
        transient=False,
    ) as progress:
        task = progress.add_task("Matching advisories…", total=len(candidates))
        for name, purls in candidates.items():
            repo_records = records_by_name.get(name) or []
            versions = _aggregate_conda_versions(repo_records)
            matched = _match_advisories(purls, osv, versions)
            if not matched:
                # OSV listed an advisory referencing the same name but our
                # conda versions don't intersect any of its ranges. Skip
                # writing a noisy empty file.
                progress.advance(task)
                continue
            source_purls = [p.to_string() for p in purls]
            latest_parsed = versions[-1].parsed if versions else None
            advisories = [
                _build_osv_record(
                    adv,
                    affected,
                    conda_package=name,
                    source_purls=source_purls,
                    conda_versions_total=len(versions),
                    latest_version=latest_parsed,
                    generated_at=generated_at,
                )
                for adv, affected in matched.values()
            ]
            # Advisories that actually hit a conda version sort first.
            advisories.sort(
                key=lambda r: (
                    not r["database_specific"]["conda-forge"]["affected_versions"]
                )
            )
            # versions is sorted ascending by rattler.Version; the last entry
            # is the newest conda-forge release. The frontend uses
            # latest_version (raw string) to surface "active on latest"
            # advisories for triage prioritization.
            latest_version = versions[-1].version if versions else None
            payload = {
                "schema_version": 1,
                "package": name,
                "purls": source_purls,
                "generated_at": generated_at,
                "conda_versions_total": len(versions),
                "latest_version": latest_version,
                "advisories": advisories,
            }
            written.append(_write_file(out_dir, name, payload))
            total_advs += len(advisories)
            total_affected_versions += sum(
                len(r["database_specific"]["conda-forge"]["affected_versions"])
                for r in advisories
            )
            progress.advance(task)

    if clean_stale and not only and not limit:
        kept = {p.stem for p in written}
        _prune_stale(out_dir, keep=kept)

    elapsed = time.monotonic() - started
    console.log(
        f"Wrote [bold]{len(written):,}[/] per-package CVE files to {out_dir} "
        f"({total_advs:,} advisories, {total_affected_versions:,} affected versions) "
        f"in {elapsed:.1f}s"
    )

    return RunSummary(
        packages_with_advisories=len(written),
        advisories_total=total_advs,
        affected_version_total=total_affected_versions,
        written_files=written,
        skipped_no_purl=skipped_no_purl,
        skipped_no_advisories=len(candidates) - len(written),
    )


def _prune_stale(out_dir: Path, keep: set[str]) -> None:
    if not out_dir.exists():
        return
    for f in out_dir.glob("*.json"):
        if f.stem not in keep:
            f.unlink()


if __name__ == "__main__":
    try:
        app()
    except KeyboardInterrupt:
        sys.exit(130)
